eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9761/eureka/
    instanceInfoReplicationIntervalSeconds: 10
    healthcheck.enabled: false
    eureka-connection-idle-timeout-seconds: 10
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
spring:
  redis:
    password: root@123456
    lettuce:
      pool:
        max-active: 100
        max-idle: 30
        max-wait: 10000
        min-idle: 20
    sentinel:
      master: mymaster
      nodes: 192.168.48.2:26379,192.168.48.2:26380,192.168.48.2:26381
    timeout: 60000
  rabbitmq:
    addresses: 192.168.48.2:5672
    username: admin
    password: root-123456
frame:
  druid:
    datasource:
      filters: stat
      maxActive: 100
      initialSize: 1
      maxWait: 3000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x' from dual
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 50
    ds:
      master:
        url: jdbc:mysql://192.168.48.21:3306/agile?serverTimezone=Asia/Shanghai&allowMultiQueries=true
        username: root
        password: root+654321
        driverClassName: com.mysql.cj.jdbc.Driver
      base:
        url: jdbc:mysql://192.168.48.21:3306/base?serverTimezone=Asia/Shanghai
        username: root
        password: root+654321
        driverClassName: com.mysql.cj.jdbc.Driver
      zentao:
        url: jdbc:mysql://192.168.48.21:3307/zentao?serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        driverClassName: com.mysql.cj.jdbc.Driver

uuidFlag: ${UUID_FLAG:""}
xxl:
  job:
    admin:
      addresses: http://localhost:9025/job
    executor:
      appname: agile-server
      ip:
      port: 10001
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 3
    accessToken:
#缺陷来源
fault:
  source: ${FAULT_SOURCE:yusys}

issue:
  regular:
    flag: true

env: ${ENV:test}

YuDO:
  url: ${YuDO_URL:192.168.48.1:8300 }
project:
  location: ${PROJECT_LOCATION:devops}
graylog:
  host: ${GRAYLOG_HOST:192.168.48.5}
  port: ${GRAYLOG_PORT:12201}
  appname: agile-server
  appenv: ${APP_ENV:dev}