eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    instanceInfoReplicationIntervalSeconds: 10
    healthcheck.enabled: false
    eureka-connection-idle-timeout-seconds: 10
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
spring:
  redis:
    password: root@123456
    lettuce:
      pool:
        max-active: 100
        max-idle: 30
        max-wait: 10000
        min-idle: 20
    sentinel:
      master: mymaster
      nodes: 192.168.48.2:26379,192.168.48.2:26380,192.168.48.2:26381
    timeout: 60000
  rabbitmq:
    addresses: 192.168.48.2:5672
    username: admin
    password: root-123456
frame:
  druid:
    datasource:
      filters: stat
      maxActive: 100
      initialSize: 1
      maxWait: 3000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x' from dual
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 50
    ds:
      master:
        url: jdbc:mysql://192.168.48.1:3306/req?serverTimezone=Asia/Shanghai&allowMultiQueries=true
        username: root
        password: root+654321
        driverClassName: com.mysql.cj.jdbc.Driver
      base:
        url: jdbc:mysql://192.168.48.1:3306/base?serverTimezone=Asia/Shanghai
        username: root
        password: root+654321
        driverClassName: com.mysql.cj.jdbc.Driver
uuidFlag: ${UUID_FLAG:""}
xxl:
  job:
    admin:
      addresses: http://localhost:8025/job
    executor:
      appname: agile-impl
      ip:
      port: 10001
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 3
    accessToken:
#缺陷来源 itc或者YuDO
fault:
  source: ${FAULT_SOURCE:itc}

chamc:
  service:
    login:
      appName: DevOps_dev
      hostName: http://10.1.8.16/
      loginAppValidateKey: dkfjeaksdi3
    mail:
      host: http://10.1.1.33:8888/
      token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJEZXZPcHNfZGV2IiwiaXNzIjoiZHAtc2VydmljZW1ndCIsInNlcnZpY2VzIjpbIm1lc3NhZ2VjZW50ZXItYXBpIiwicmVnaXN0cnktY2VudGVyIiwidXNlcmNlbnRlci1hcGkiXSwiZXhwIjoxNjA5MzQ0MDAwLCJpYXQiOjE1ODc4NzIwMTB9.2KlfOsbbm8NMdc1msw-BcY242yrHMuoHmgoDUAd5PhMlm4eHe30ltjozPg2qPOND6fs7oYX8m2tCf7U2Ri8Y_MzIZQN0VWpH3V8HHgVLu_e59_HsuQvvopAPoMqdnazqmL5n2-9QvjT0KyKAMWKhQqYGqoe2_pNv9gLBUytllfs
    usercenter:
      token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJEZXZPcHNfZGV2IiwiaXNzIjoiZHAtc2VydmljZW1ndCIsInNlcnZpY2VzIjpbIm1lc3NhZ2VjZW50ZXItYXBpIiwicmVnaXN0cnktY2VudGVyIiwidXNlcmNlbnRlci1hcGkiXSwiZXhwIjoxNjA5MzQ0MDAwLCJpYXQiOjE1ODcxMDAxMzd9.VFVi-uEYwtykH8DnJfLpeQx8vMJY5xg1MwbSfey23CJx2iYqNgkgo_YsCPKLSVieB1njTjgY1lhl-7Rkj46ybEY6OnnQGE5H0zTidCvF8UKA8sLR2gCsU-dXjtbuqrqJpCi2XDUeIs5VNzRMA7Xy2cI-t1GIlx3Bh858qZoOLTM
      basePath: http://10.1.8.187:8080
    syncProject:
      url: http://10.1.8.112:8080/DevMgmt/DevOpsConnector/syncProjects

issue:
  regular:
    flag: true

env: ${ENV:test}

YuDO:
  url: ${YuDO_URL:192.168.48.1:8300 }
project:
  location: ${PROJECT_LOCATION:devops}